from utils.data_processing import load_data_dict, get_data
from conf.eeg_channel_picks import hackathon
from conf.eeg_channel_order import standard_19_channel
from conf.eeg_annotations import braincapture_annotations, tuh_eeg_artefact_annotations